
services:
  grpc-server:
    build: .
    command: python server.py
    volumes:
      - .:/app
    ports:
      - "50051:50051"
    networks:
      - grpc-net

  grpc-client:
    build: .
    command: python client.py
    volumes:
      - .:/app
    networks:
      - grpc-net

networks:
  grpc-net:
    driver: bridge
