# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from comunicacao_grpc import mensagens_pb2 as comunicacao__grpc_dot_mensagens__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in comunicacao_grpc/mensagens_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MensagemStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FuncaoVoid = channel.unary_unary(
                '/Mensagem/FuncaoVoid',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.FuncaoLong = channel.unary_unary(
                '/Mensagem/FuncaoLong',
                request_serializer=comunicacao__grpc_dot_mensagens__pb2.MensagemLong.SerializeToString,
                response_deserializer=comunicacao__grpc_dot_mensagens__pb2.MensagemLong.FromString,
                _registered_method=True)
        self.FuncaoVariosLong = channel.unary_unary(
                '/Mensagem/FuncaoVariosLong',
                request_serializer=comunicacao__grpc_dot_mensagens__pb2.MensagemVariosLong.SerializeToString,
                response_deserializer=comunicacao__grpc_dot_mensagens__pb2.MensagemVariosLong.FromString,
                _registered_method=True)
        self.FuncaoString = channel.unary_unary(
                '/Mensagem/FuncaoString',
                request_serializer=comunicacao__grpc_dot_mensagens__pb2.MensagemString.SerializeToString,
                response_deserializer=comunicacao__grpc_dot_mensagens__pb2.MensagemString.FromString,
                _registered_method=True)
        self.FuncaoComplexa = channel.unary_unary(
                '/Mensagem/FuncaoComplexa',
                request_serializer=comunicacao__grpc_dot_mensagens__pb2.MensagemComplexa.SerializeToString,
                response_deserializer=comunicacao__grpc_dot_mensagens__pb2.MensagemComplexa.FromString,
                _registered_method=True)


class MensagemServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FuncaoVoid(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FuncaoLong(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FuncaoVariosLong(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FuncaoString(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FuncaoComplexa(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MensagemServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FuncaoVoid': grpc.unary_unary_rpc_method_handler(
                    servicer.FuncaoVoid,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'FuncaoLong': grpc.unary_unary_rpc_method_handler(
                    servicer.FuncaoLong,
                    request_deserializer=comunicacao__grpc_dot_mensagens__pb2.MensagemLong.FromString,
                    response_serializer=comunicacao__grpc_dot_mensagens__pb2.MensagemLong.SerializeToString,
            ),
            'FuncaoVariosLong': grpc.unary_unary_rpc_method_handler(
                    servicer.FuncaoVariosLong,
                    request_deserializer=comunicacao__grpc_dot_mensagens__pb2.MensagemVariosLong.FromString,
                    response_serializer=comunicacao__grpc_dot_mensagens__pb2.MensagemVariosLong.SerializeToString,
            ),
            'FuncaoString': grpc.unary_unary_rpc_method_handler(
                    servicer.FuncaoString,
                    request_deserializer=comunicacao__grpc_dot_mensagens__pb2.MensagemString.FromString,
                    response_serializer=comunicacao__grpc_dot_mensagens__pb2.MensagemString.SerializeToString,
            ),
            'FuncaoComplexa': grpc.unary_unary_rpc_method_handler(
                    servicer.FuncaoComplexa,
                    request_deserializer=comunicacao__grpc_dot_mensagens__pb2.MensagemComplexa.FromString,
                    response_serializer=comunicacao__grpc_dot_mensagens__pb2.MensagemComplexa.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Mensagem', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Mensagem', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Mensagem(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FuncaoVoid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Mensagem/FuncaoVoid',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FuncaoLong(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Mensagem/FuncaoLong',
            comunicacao__grpc_dot_mensagens__pb2.MensagemLong.SerializeToString,
            comunicacao__grpc_dot_mensagens__pb2.MensagemLong.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FuncaoVariosLong(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Mensagem/FuncaoVariosLong',
            comunicacao__grpc_dot_mensagens__pb2.MensagemVariosLong.SerializeToString,
            comunicacao__grpc_dot_mensagens__pb2.MensagemVariosLong.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FuncaoString(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Mensagem/FuncaoString',
            comunicacao__grpc_dot_mensagens__pb2.MensagemString.SerializeToString,
            comunicacao__grpc_dot_mensagens__pb2.MensagemString.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FuncaoComplexa(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Mensagem/FuncaoComplexa',
            comunicacao__grpc_dot_mensagens__pb2.MensagemComplexa.SerializeToString,
            comunicacao__grpc_dot_mensagens__pb2.MensagemComplexa.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
